### ISSUE TITLE
Bonjour !

### ISSUE THREAD

**Issue by alexandre-laine** [victor-amblard/analyse-legislatives-2024#1]
Bonjour, 

Je m'appelle [Alexandre](https://github.com/alexandre-laine) et je suis actuellement une formation de data sciences au seins de la faculté des Sciences d'Aix-Marseille. Pour celle-ci, je travail sur un projet visant à étudier et modéliser le report des voix entre les deux tours des élections législatives en utilisant l'apprentissage automatique. Je suis tombé sur ton repository en regardant sur github et je trouve ton approche intéressante, est ce que tu aurai une adresse mail sur laquelle je puisse t'écrire pour en discuter ?

En te souhaitant une bonne journée.
Alexandre

**Comment by victor-amblard** [comment]
Bonjour Alexandre, tu peux m'envoyer un mail à victor-code [at] proton [dot] me
